As STANBOL-1132 introduced new ValueTypeParser there is now the possibility the the ServiceLoader encounters NoClassDefFoundError when loading ValueTypeParser services. This e.g. happens if one uses version 0.11.0-SNAPSHOT of the nlp-json module with the 0.10.0 version of the nlp. To avoid that such cases do cause the initialisation to fail the code now catches such exceptions. This allows to write/parse AnalysedText instances that do not use Values of the failing types.
git-svn-id: https://svn.apache.org/repos/asf/stanbol/trunk@1532330 13f79535-47bb-0310-9956-ffa450edef68